version: '3.8'

services:
  barrier-service:
    build:
      context: .
    container_name: barrier_service
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:stable
    container_name: barrier_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - barrier-service
    restart: unless-stopped